resource_types:
- name: docker-image-multitag
  type: docker-image
  privileged: true
  source:
    repository: jerithorg/docker-image-resource
    tag: latest
    registry_mirror: ((registry-mirror))

resources:
- name: rapidpro-docker
  type: git
  source:
    uri: https://github.com/praekeltfoundation/rapidpro-docker
    branch: master
  webhook_token: prod-my-resource
  check_every: 30m

- name: rapidpro-image
  type: docker-image-multitag
  source:
    repository: praekeltfoundation/rapidpro
    username: ((rapidpro-dockerhub-username))
    password: ((rapidpro-dockerhub-password))
    registry_mirror: ((registry-mirror))
  check_every: 30m

jobs:
- name: build-image
  plan:
  - get: rapidpro-docker
    trigger: true
  - task: build
    file: rapidpro-docker/.ci/build.yml
    params:
        VERSION_SUFFIX: ((version-suffix))
  - put: rapidpro-image
    params:
      build: rapidpro-docker
      tag: image-params/tag
      additional_tags: image-params/additional_tags
      tag_as_latest: false
      cache: ((cache))
      cache_tag: ((cache-tag))
      build_args_file: image-params/build-args.json
